### ISSUE TITLE
iRate fails cause my app can't be found on Itunes

### ISSUE THREAD

**Issue by therauli** [nicklockwood/iRate#106]
When I try to use iRate I always get this error message:
iRate rating process failed because: The application could not be found on the App Store.

I have triple checked the appStoreID from iTunesConnect. My app is basically following the Events demo in this repo.

**Comment by SushilSharma12** [comment]
Hello Nick,
My app not live in app store but in itunes connect for test flight testing. I also have app id from itunes connect. iRate still gives error " iRate rating process failed because: The application could not be found on the App Store. "
So can I test the iRate or should I should for app release ?

**Comment by nicklockwood** [comment]
iRate checks the iTunes JSON feed, so it won't work until the app is actually live. If it gets as far as showing that error though, everything is working fine.
